// <auto-generated />
using Dws.Note_one.Api.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace note_one_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230112141452_CostumersTable")]
    partial class CostumersTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("Dws.Note_one.Api.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Name = "Fruits and Vegetables"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Dairy"
                        });
                });

            modelBuilder.Entity("Dws.Note_one.Api.Domain.Models.Costumer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Credit")
                        .HasColumnType("REAL");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Costumers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Credit = -10.5,
                            Email = "viniciusfake@gmail.com",
                            Name = "Vinicius Cortêz",
                            PhoneNumber = "+55 (85) 11111-1111"
                        },
                        new
                        {
                            Id = 2,
                            Credit = 1984.0,
                            Email = "iamnotbatman@gmail.com",
                            Name = "Bruce Wayne",
                            PhoneNumber = "+55 (85) 22222-2222"
                        },
                        new
                        {
                            Id = 3,
                            Credit = 451.0,
                            Email = "iamironman@gmail.com",
                            Name = "Antony Stark",
                            PhoneNumber = "+55 (85) 33333-3333"
                        },
                        new
                        {
                            Id = 4,
                            Credit = -200.88999999999999,
                            Email = "iamnotmiranha@gmail.com",
                            Name = "Peter Parker",
                            PhoneNumber = "+21 (44) 44444-4444"
                        });
                });

            modelBuilder.Entity("Dws.Note_one.Api.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<short>("QuantityInPackage")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("UnitOfMeasurement")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 101,
                            Name = "Milk",
                            QuantityInPackage = (short)10,
                            UnitOfMeasurement = (byte)5
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 100,
                            Name = "Apple",
                            QuantityInPackage = (short)1,
                            UnitOfMeasurement = (byte)4
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 100,
                            Name = "Onion",
                            QuantityInPackage = (short)20,
                            UnitOfMeasurement = (byte)4
                        });
                });

            modelBuilder.Entity("Dws.Note_one.Api.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Login = "vini",
                            Password = "12345"
                        });
                });

            modelBuilder.Entity("Dws.Note_one.Api.Domain.Models.Product", b =>
                {
                    b.HasOne("Dws.Note_one.Api.Domain.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Dws.Note_one.Api.Domain.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
